apiVersion: faasshare.tum/v1
kind: SharePod
metadata:
  name: resnet
  namespace: faas-share-fn
  labels:
    "com.openfaas.scale.max": "9"
    "com.openfaas.scale.min": "9"
  annotations:
    "kubeshare/gpu_request": "0.05"
    "kubeshare/gpu_limit": "1.0"
    "kubeshare/gpu_mem": "1073741824"
spec:
  replicas: 9
  podSpec:
    terminationGracePeriodSeconds: 1
    containers:
      - name: resnet
        image: yukiozhu/mlperf-faas-resnet:pytorch
        env:
          #- name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
          #  value: "12"
          - name: LD_PRELOAD
            value: ""
        ports:
          - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: "model-volume"
            mountPath: "/models/"
    volumes:
      - name: "model-volume"
        hostPath:
          path: "/models/"


